name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/docker-demo || git clone https://github.com/o888o88o44/docker-demo.git
            cd docker-demo
            git pull
            docker stop app || true
            docker rm app || true
            docker build -t docker-demo-app .
            docker run -d -p 8080:8080 --name app docker-demo-app